#!/bin/sh
echo "------------"
echo "Running git pre-push hook. Running Spotless Check... "
echo "------------"

git stash -q --keep-index

./gradlew spotlessCheck

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
else
    echo "------------"
    echo 1>&2 "Spotless Check found violations."
    echo "Run spotless apply in your terminal and fix the issues before trying to push again."
    echo "------------"
fi

git stash pop -q

exit $status