[versions]

[libraries]

# Regular Libraries
detekt-rules-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version ="1.23.8" }

# Kotlinx
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.11.0" }

# SLF4J
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.18"}
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.18"}

# Lets-Plot
letsplot-kotlinjvm = { group = "org.jetbrains.lets-plot", name = "lets-plot-kotlin-jvm", version = "4.15.0" }
letsplot-imageexport = { group = "org.jetbrains.lets-plot", name = "lets-plot-image-export", version = "4.8.2" }

# Tests
kotlin-test = { group = "org.jetbrains.kotlin", name="kotlin-test" }

# JUnit
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.1.3" }

[plugins]
task-tree = { id = "com.dorongold.task-tree", version = "4.0.2" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
spotless = { id = "com.diffplug.spotless", version = "8.10.0" }
git-versioning = { id = "me.qoomon.git-versioning", version = "6.4.4" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
dokka = { id = "org.jetbrains.dokka", version = "2.2.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.4.10" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.3.0" }
